<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mapster" Version="7.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="7.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="7.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.18" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="Serilog.Sinks.Map" Version="1.0.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Ensuranx.Application\Ensuranx.Application.csproj" />
		<ProjectReference Include="..\Ensuranx.Common\Ensuranx.Common.csproj" />
		<ProjectReference Include="..\Ensuranx.Domain\Ensuranx.Domain.csproj" />
		<ProjectReference Include="..\Ensuranx.Infrastructure.Shared\Ensuranx.Infrastructure.Shared.csproj" />
		<ProjectReference Include="..\Ensuranx.Infrastructure\Ensuranx.Infrastructure.csproj" />
		<ProjectReference Include="..\Ensuranx.Logger\Ensuranx.Logger.csproj" />
	</ItemGroup>

</Project>
